### ISSUE TITLE
Create task lists template

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/.github#14]
### Purpose
Used for trackers, mainly in the tasks repository. Add guidelines to templates

### Task list guidelines
- Add task list and sub tasks to project
    - Clear task list status
- In a sub task PR if there isn’t a sub task issue, reference but do not resolve the task lisk (this should go in the PR template)
- In the task list, once sub task PR is merged and there isn’t a sub task issue, manually mark it complete in task list

**Comment by colinli02** [comment]
Awaiting someone to verify this is what was expected of a task list template in my PR

**Comment by colinli02** [comment]
Modified with discussion in last INFRA meeting, tagged reviewer for review before merge

**Comment by colinli02** [comment]
Updated with Patrick's latest comments and with new github features.

**Comment by colinli02** [comment]
Re-solved all conversations within PR, made minimal change with latest commit, can merge.
