### ISSUE TITLE
Create starter workflows

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/.github#3]
### Purpose
Make template for common workflows

### Changes
Add docs-deploy, docs-lint, and docs-scheduled-tasks workflow templates based on the workflows in [UBCSailbot/docs](https://github.com/UBCSailbot/docs)

### Relevant Resources
- https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization
- https://github.com/UBCSailbot/docs/tree/main/.github/workflows

**Comment by patrick-5546** [comment]
A more powerful alternative to consider is template repositories: https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by patrick-5546** [comment]
Not important, can just copy paste for now

**Comment by colinli02** [comment]
https://github.com/UBCSailbot/.github/tree/user/colinli02/3_create_starter_workflows

Made a branch for these starter workflows. Just curious, is there a way to test these workflow actions?

**Comment by patrick-5546** [comment]
- Closed in favor of https://github.com/UBCSailbot/network_systems/issues/11
